### PR TITLE
Added more redirects

### PR DESCRIPTION
**Pull request by DeleteThisAcount**
For world and jokebook

### CODE REVIEW

**Comment by joker314** [comment]
Hmm, is this really the point of isOnline? We don't want to abuse our position to let more people find our accounts.

I'll leave this open for further discussion.

**Comment by DeleteThisAcount** [comment]
Well... I guess. If we shoulnt we should just make isOnline2 be a redirect to isOnlineV2

(btw I'm going to keep this version on :P I keep forgetting the 1 at the end of your name and the _ in world_languages)

**Comment by WorldLanguages** [comment]
We don't want to abuse our position to let more people find our accounts.

**Comment by DeleteThisAcount** [comment]
Okay! Should I just make isonline2 redirect to @isOnlinev2? It would make more sence. Or no?
Right now only isonline redirects... but 2 has a ton of links

**Comment by joker314** [comment]
Hmm.. I haven't seen too many incorrect links -- but if this is a problem, then I agree that we should add a redirect.

**Comment by WorldLanguages** [comment]
@DeleteThisAcount Have discord.gg account?

**Comment by WorldLanguages** [comment]
@DeleteThisAcount u here?

**Comment by DeleteThisAcount** [comment]
yes

**Pull request closed without merging**
