### PR TITLE
Make World Langauges into a real dev

### PR DESCRIPTION
**Pull request by DeleteThisAcount**
the dev thing wasnt working on their name... this (should) fix it.

(Im not sure)

### CODE REVIEW

**Comment by DeleteThisAcount** [comment]
... it says I didnt change anything

**Comment by DeleteThisAcount** [comment]
nm delete this

**Comment by joker314** [comment]
Perhaps you accidentally removed some code, causing the issue to arise, then when you re-added the code it fixed?

**Comment by DeleteThisAcount** [comment]
nope... I just reinstalled and its still there

**Comment by DeleteThisAcount** [comment]
I mean I reinstalled and the Io dev is gone

**Comment by joker314** [comment]
Well.. that's quite strange *shrugs*

**Pull request closed without merging**
