### PR TITLE
world_languages to World_Languages

### PR DESCRIPTION
**Pull request by DeleteThisAcount**
tada!

### CODE REVIEW

**Comment by Sheshank-s** [comment]
I don't think this is necessary

**Comment by joker314** [comment]
I disagree, this URL is better since it's consistent with the rest of the site (and so browsers can understand that, since they might not know that it leads to the same place).

**Comment by Sheshank-s** [comment]
Ok i guess.

**Comment by DeleteThisAcount** [comment]
Thanks, @joker314

**Pull request merged**
