### PR TITLE
added more FAQ

### PR DESCRIPTION
**Pull request by DeleteThisAcount**
added about the why is it v2 question.

### CODE REVIEW

**Comment by Sheshank-s** [comment]
Thanks for all the hard work :D

**Comment by DeleteThisAcount** [comment]
Your welcome! (my coding knowledge isnt much but I can do stuff like this and simple stuff)

**Comment by Sheshank-s** [comment]
Haha, are you a beta tester?

**Comment by DeleteThisAcount** [comment]
@GreenBayRules what do you mean?

**Pull request merged**
